[colors]
bg = #1e1e2e
;bg = #801e1e2e ;bg a 50% de 
;bg = #4D1e1e2e 30%
;bg = #331e1e2e ; 20%
fg = #cdd6f4
red = #f38ba8
blue = #89b4fa
yellow = #f9e2af
green = #a6e3a1

[bar/mybar]
width = 100%
height = 30
background = ${colors.bg}
foreground = ${colors.fg}
font-0 = Iosevka Nerd Font:size=12;2

modules-left = sep power sep
modules-center = sep date sep
;modules-right = volume wifi iface
modules-right =battery sep cpu sep ram sep volume sep iface sep wifi

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; POWER BUTTON
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[module/power]
type = custom/menu
expand-right = true

format-spacing = 1
label-open = " Session"
label-open-foreground = ${colors.red}

label-close = "  Close"
label-close-foreground = ${colors.red}

label-separator = |

menu-0-0 = "reboot"
menu-0-0-exec = menu-open-1

menu-0-1 = "power off"
menu-0-1-exec = menu-open-2

menu-0-2 = "lock screen"
menu-0-2-exec = menu-open-3

menu-1-0 = "reboot"
menu-1-0-exec = sudo reboot

menu-1-1 = "cancel "
menu-1-1-exec = menu-open-0

menu-2-0 = "power off"
menu-2-0-exec = sudo poweroff

menu-2-1 = "cancel "
menu-2-1-exec = menu-open-0

menu-3-0 = "lock screen"
menu-3-0-exec = i3lock -c 000000

menu-3-1 = "cancel "
menu-3-1-exec = menu-open-0
 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DATE CENTER
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/date]
type = internal/date
interval = 1
date = %A %d %B  %H:%M
format = <label>
label =   %date%
format-foreground = ${colors.blue}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; VOLUME (i3blocks)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; [module/volume]
; type = custom/script
; exec = /usr/share/i3blocks/volume
; interval = 1
; format-prefix = "  "
; label = %output%
; format = <label>
; click-left = amixer -D pulse sset Master toggle
; scroll-up = amixer -D pulse sset Master 5%+
; scroll-down = amixer -D pulse sset Master 5%-

[module/volume]
type = internal/pulseaudio
format-volume-prefix = "  "
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = " MUTED"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SEPARATOR
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/sep]
type = custom/text
format = "     "
format-foreground = ${colors.blue}


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; CPU 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
label = %percentage:2%%

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; RAM 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/ram]
type = internal/memory
interval = 2
format-prefix = "  "
label = %percentage_used:2%%
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; WIFI (i3blocks)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/wifi]
type = custom/script
exec = /usr/share/i3blocks/wifi
interval = 3
format-prefix = "  "
label = %output%
format = <label>

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; INTERFACE / IP
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/iface]
type = custom/script
exec = /usr/share/i3blocks/iface
interval = 2
format-prefix = "IP:  " 
label = %output%
format = <label>

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; BATTERY
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/battery]
type = custom/script
exec = /usr/share/i3blocks/battery
interval = 5

format-prefix = "  "
format-prefix-foreground = ${colors.green}

format = <label>
format-foreground = ${colors.fg}
label-charging = %output% (Charging)
label-discharging = %output% (Discharging)
label-full = %output% (Full)
